### PR TITLE
Save roast csv

### PR DESCRIPTION
**Pull request by tblanarik**
Hey guys - I wanted to be able to save the raw values of my graph as a CSV instead of only as a png.
I hope this works for you. I didn't give my menu item a shortcut key because I wasn't sure which one you'd like it to have (if any).
Please let me know if you see any issues and I'll be happy to fix them.

Openroast is really great by the way. It's totally breathed new life in to my home roasting hobby.

### CODE REVIEW

**Comment by tblanarik** [comment]
Outlook looks like this, by the way:

`Seconds,Temperature
0,150
1,150
2,150
3,150
4,154
5,173
6,195
7,218
8,237
9,246
10,252
11,254
12,253
13,249
`

**Comment by int3ll3ct** [comment]
Thanks Trevor, I will code review later this week and fold into an eventual
1.3 release, if that's ok with you. in3ll3ct

On Sep 4, 2017 1:57 AM, "Trevor" <notifications@github.com> wrote:

Hey guys - I wanted to be able to save the raw values of my graph as a CSV
instead of only as a png.
I hope this works for you. I didn't give my menu item a shortcut key
because I wasn't sure which one you'd like it to have (if any).
Please let me know if you see any issues and I'll be happy to fix them.

Openroast is really great by the way. It's totally breathed new life in to
my home roasting hobby.
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/Roastero/Openroast/pull/64
Commit Summary

   - added plumbing for saving roast graph as csv.
   - save time and temperature values to the selected CSV file
   - converting x value to elapsed time in seconds for CSV output

File Changes

   - *M* openroast/views/customqtwidgets.py
   <https://github.com/Roastero/Openroast/pull/64/files#diff-0> (20)
   - *M* openroast/views/mainwindow.py
   <https://github.com/Roastero/Openroast/pull/64/files#diff-1> (5)
   - *M* openroast/views/roasttab.py
   <https://github.com/Roastero/Openroast/pull/64/files#diff-2> (3)

Patch Links:

   - https://github.com/Roastero/Openroast/pull/64.patch
   - https://github.com/Roastero/Openroast/pull/64.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Roastero/Openroast/pull/64>, or mute the thread

**Comment by tblanarik** [comment]
Sounds great, thanks!

**Comment by int3ll3ct** [comment]
I haven't tested this, but upon visual inspection, seems fine, merging into master.

**Pull request merged**
